const path = require('node:path');
const { FusesPlugin } = require('@electron-forge/plugin-fuses');
const { FuseV1Options, FuseVersion } = require('@electron/fuses');

// The application icons generated by "npm run build-icons". The packager icon is given without an extension on purpose, because it
// picks the .icns or .ico file itself per platform, while the makers below each want one specific file.
const iconBasePath = path.join(__dirname, 'assets', 'icon');

module.exports = {
	packagerConfig: {
		asar: true,
		icon: iconBasePath,

		// The identity the operating systems keep Spiccioli under. Without these the packager falls back to Electron's own defaults, which
		// name the application after Electron rather than after Spiccioli and file it under developer tools.
		//
		// The bundle identifier is the one value here that cannot be changed lightly once Spiccioli is installed anywhere: macOS keeps
		// permissions, window state and launch services entries under it, and a new identifier reads as a different application. It is
		// in the "io.github" namespace because that is the repository hosting Spiccioli and therefore the only reversed domain name that
		// is unambiguously ours.
		appBundleId: 'io.github.simone3.spiccioli',
		appCategoryType: 'public.app-category.finance',
		ignore: [
			// The icons are read from the repository at package time, so they do not need to be copied into the application itself
			/^\/assets($|\/)/,
			/^\/\.vscode($|\/)/,
			/^\/coverage($|\/)/,
			/^\/node_modules\/\.cache($|\/)/,
			/^\/out($|\/)/,
			/^\/tests($|\/)/
		]
	},
	rebuildConfig: {},
	makers: [
		{
			name: '@electron-forge/maker-squirrel',
			config: {
				// "productName" names the executable the packager writes, so the installer has to look for that same name rather than for
				// the lowercase package name it would otherwise assume. The identifier itself stays free of spaces because it also becomes
				// the package name Squirrel keeps the installation under.
				name: 'Spiccioli',
				exe: 'Spiccioli.exe',
				setupExe: 'Spiccioli-Setup.exe',
				setupIcon: `${iconBasePath}.ico`
			}
		},
		{
			name: '@electron-forge/maker-zip',
			platforms: [ 'darwin' ]
		},
		{
			name: '@electron-forge/maker-deb',
			config: {
				options: {
					// Linux package names are conventionally lowercase, while the binary inside the package is the one the packager wrote
					name: 'spiccioli',
					productName: 'Spiccioli',
					bin: 'Spiccioli',
					icon: `${iconBasePath}.png`
				}
			}
		},
		{
			name: '@electron-forge/maker-rpm',
			config: {
				options: {
					name: 'spiccioli',
					productName: 'Spiccioli',
					bin: 'Spiccioli',
					icon: `${iconBasePath}.png`
				}
			}
		}
	],
	plugins: [
		{
			name: '@electron-forge/plugin-auto-unpack-natives',
			config: {}
		},

		// Fuses are used to enable/disable various Electron functionality
		// at package time, before code signing the application
		new FusesPlugin({
			version: FuseVersion.V1,
			[FuseV1Options.RunAsNode]: false,
			[FuseV1Options.EnableCookieEncryption]: true,
			[FuseV1Options.EnableNodeOptionsEnvironmentVariable]: false,
			[FuseV1Options.EnableNodeCliInspectArguments]: false,
			[FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true,
			[FuseV1Options.OnlyLoadAppFromAsar]: true
		})
	]
};
